version: '3.1'
services:

  wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    command: "--global-response-templating --enable-stub-cors" # add command `--verbose` to output verbose request matching
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
    ports:
      - "9091:8080"

  gotenberg:
    image: gotenberg/gotenberg:8.14.1
    networks:
      - hmpps_int
    container_name: gotenberg
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3000"
    command:
      - "gotenberg"
      - "--chromium-ignore-certificate-errors"
      - "--pdfengines-merge-engines=pdftk"
      - "--libreoffice-disable-routes"
      - "--webhook-disable"
      - "--prometheus-disable-collect"
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3001/health' ]

networks:
  hmpps_int:
