---
generic-service:
  replicaCount: 2

  ingress:
    host: historical-prisoner-dev.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://historical-prisoner-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HISTORICAL_PRISONER_API_URL: "https://historical-prisoner-api-dev.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

  scheduledDowntime:
    enabled: true
    startup: '22 6 * * 1-5' # Start at 6.22am UTC Monday-Friday
    shutdown: '52 21 * * 1-5' # Stop at 9.52pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-alerts-non-prod
