---
# Per environment values which override defaults in hmpps-historical-prisoner/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: historical-prisoner-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://historical-prisoner-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.prison.service.justice.gov.uk/auth"
    HISTORICAL_PRISONER_API_URL: "https://historical-prisoner-api-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: syscon-alerts-non-prod
