---
generic-service:
  replicaCount: 2

  ingress:
    host: historical-prisoner-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://historical-prisoner-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HISTORICAL_PRISONER_API_URL: "https://historical-prisoner-api-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: https://frontend-components-preprod.hmpps.service.justice.gov.uk
    DPS_URL: https://digital-preprod.prison.service.justice.gov.uk
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

  scheduledDowntime:
    enabled: true
    startup: '50 6 * * 1-5' # Start at 6.40am UTC Monday-Friday
    shutdown: '50 20 * * 1-5' # Stop at 8.50pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-alerts-non-prod
